### ISSUE TITLE
Spark RDD概述

### ISSUE THREAD

**Issue by turboFei** [netease-bigdata/ne-spark-courseware#3]
## 题名

Spark RDD 概述

## 摘要

概述RDD的定义特点、API、作业划分与缓存的使用等。

## 大纲

- 自我介绍
- 目录
- RDD定义及特点  

    - 定义
    - 内存中分区
    - lazy执行
    - 弹性、容错
- RDD Operations 
    - transformation 
    - action触发job提交
    - RDD lineage
- RDD 依赖
    - 窄依赖
    - 宽依赖 划分stage
- RDD与Task
    - rdd分区与task
    - 并行度与内存压力
- RDD Persist
    - 合理缓存的必要
    - 缓存级别
- 相关链接
    - RDD官方文档
    - RDD论文
- 谢谢

## 附录

【在这里描述你的主题涵盖的其他信息】

**Comment by hustfeiwang** [comment]
@yaooqinn http://ogk82bfkr.bkt.clouddn.com/RDDBasic.html
先上传一个，后续再修改
